// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.3
// source: tmdatabase/tmdatabase_rr.proto

package tm2_proto_tmdatabase

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserBasicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserBasicRequest) Reset() {
	*x = GetUserBasicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicRequest) ProtoMessage() {}

func (x *GetUserBasicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicRequest.ProtoReflect.Descriptor instead.
func (*GetUserBasicRequest) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserBasicRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserBasicReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *UserBasic `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetUserBasicReply) Reset() {
	*x = GetUserBasicReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicReply) ProtoMessage() {}

func (x *GetUserBasicReply) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicReply.ProtoReflect.Descriptor instead.
func (*GetUserBasicReply) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserBasicReply) GetValue() *UserBasic {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetUserBasicReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUserBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserBalanceRequest) Reset() {
	*x = GetUserBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceRequest) ProtoMessage() {}

func (x *GetUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBalanceRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserBalanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *UserBalance `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error string       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetUserBalanceReply) Reset() {
	*x = GetUserBalanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceReply) ProtoMessage() {}

func (x *GetUserBalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceReply.ProtoReflect.Descriptor instead.
func (*GetUserBalanceReply) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserBalanceReply) GetValue() *UserBalance {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetUserBalanceReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUserStartGameInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserStartGameInfoRequest) Reset() {
	*x = GetUserStartGameInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserStartGameInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStartGameInfoRequest) ProtoMessage() {}

func (x *GetUserStartGameInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStartGameInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserStartGameInfoRequest) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserStartGameInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserStartGameInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *UserStartGameInfo `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error string             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetUserStartGameInfoReply) Reset() {
	*x = GetUserStartGameInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserStartGameInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStartGameInfoReply) ProtoMessage() {}

func (x *GetUserStartGameInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStartGameInfoReply.ProtoReflect.Descriptor instead.
func (*GetUserStartGameInfoReply) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserStartGameInfoReply) GetValue() *UserStartGameInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetUserStartGameInfoReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateBotPlayersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the bot players whose game belongs to
	GameID int32 `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	// bot players name prefix
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// bot players initia score (should be big enough to meet all game rooms' minimum bet requirement)
	Score int64 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	// number of bot players request to be created
	Number int32 `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *CreateBotPlayersRequest) Reset() {
	*x = CreateBotPlayersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBotPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotPlayersRequest) ProtoMessage() {}

func (x *CreateBotPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotPlayersRequest.ProtoReflect.Descriptor instead.
func (*CreateBotPlayersRequest) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBotPlayersRequest) GetGameID() int32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *CreateBotPlayersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBotPlayersRequest) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CreateBotPlayersRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type CreateBotPlayersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*UserBasic `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Error  string       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateBotPlayersReply) Reset() {
	*x = CreateBotPlayersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBotPlayersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotPlayersReply) ProtoMessage() {}

func (x *CreateBotPlayersReply) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotPlayersReply.ProtoReflect.Descriptor instead.
func (*CreateBotPlayersReply) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{7}
}

func (x *CreateBotPlayersReply) GetValues() []*UserBasic {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *CreateBotPlayersReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListBotPlayersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// which game's bot players
	GameID int32 `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListBotPlayersRequest) Reset() {
	*x = ListBotPlayersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBotPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBotPlayersRequest) ProtoMessage() {}

func (x *ListBotPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBotPlayersRequest.ProtoReflect.Descriptor instead.
func (*ListBotPlayersRequest) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{8}
}

func (x *ListBotPlayersRequest) GetGameID() int32 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *ListBotPlayersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListBotPlayersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBotPlayersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*UserBasic `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Offset int32        `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32        `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count  int32        `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Error  string       `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ListBotPlayersReply) Reset() {
	*x = ListBotPlayersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBotPlayersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBotPlayersReply) ProtoMessage() {}

func (x *ListBotPlayersReply) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBotPlayersReply.ProtoReflect.Descriptor instead.
func (*ListBotPlayersReply) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{9}
}

func (x *ListBotPlayersReply) GetValues() []*UserBasic {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ListBotPlayersReply) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListBotPlayersReply) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBotPlayersReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListBotPlayersReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *GameDetail `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{10}
}

func (x *CreateGameRequest) GetValue() *GameDetail {
	if x != nil {
		return x.Value
	}
	return nil
}

type CreateGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *GameDetail `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateGameReply) Reset() {
	*x = CreateGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameReply) ProtoMessage() {}

func (x *CreateGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameReply.ProtoReflect.Descriptor instead.
func (*CreateGameReply) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{11}
}

func (x *CreateGameReply) GetValue() *GameDetail {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CreateGameReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListGamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListGamesRequest) Reset() {
	*x = ListGamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesRequest) ProtoMessage() {}

func (x *ListGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesRequest.ProtoReflect.Descriptor instead.
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{12}
}

func (x *ListGamesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListGamesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListGamesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*GameDetail `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Offset int32         `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32         `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count  int32         `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Error  string        `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ListGamesReply) Reset() {
	*x = ListGamesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGamesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesReply) ProtoMessage() {}

func (x *ListGamesReply) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesReply.ProtoReflect.Descriptor instead.
func (*ListGamesReply) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{13}
}

func (x *ListGamesReply) GetValues() []*GameDetail {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ListGamesReply) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListGamesReply) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListGamesReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListGamesReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetGameByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGameByIDRequest) Reset() {
	*x = GetGameByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByIDRequest) ProtoMessage() {}

func (x *GetGameByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByIDRequest.ProtoReflect.Descriptor instead.
func (*GetGameByIDRequest) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{14}
}

func (x *GetGameByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGameByIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *GameDetail `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetGameByIDReply) Reset() {
	*x = GetGameByIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByIDReply) ProtoMessage() {}

func (x *GetGameByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByIDReply.ProtoReflect.Descriptor instead.
func (*GetGameByIDReply) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{15}
}

func (x *GetGameByIDReply) GetValue() *GameDetail {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetGameByIDReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetGameByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetGameByNameRequest) Reset() {
	*x = GetGameByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByNameRequest) ProtoMessage() {}

func (x *GetGameByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByNameRequest.ProtoReflect.Descriptor instead.
func (*GetGameByNameRequest) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{16}
}

func (x *GetGameByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGameByNameRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetGameByNameRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetGameByNameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*GameDetail `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Offset int32         `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32         `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count  int32         `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Error  string        `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetGameByNameReply) Reset() {
	*x = GetGameByNameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameByNameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByNameReply) ProtoMessage() {}

func (x *GetGameByNameReply) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByNameReply.ProtoReflect.Descriptor instead.
func (*GetGameByNameReply) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{17}
}

func (x *GetGameByNameReply) GetValues() []*GameDetail {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GetGameByNameReply) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetGameByNameReply) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetGameByNameReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetGameByNameReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *GameDetail `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpdateGameRequest) Reset() {
	*x = UpdateGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameRequest) ProtoMessage() {}

func (x *UpdateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameRequest) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateGameRequest) GetValue() *GameDetail {
	if x != nil {
		return x.Value
	}
	return nil
}

type UpdateGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *GameDetail `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpdateGameReply) Reset() {
	*x = UpdateGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameReply) ProtoMessage() {}

func (x *UpdateGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameReply.ProtoReflect.Descriptor instead.
func (*UpdateGameReply) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateGameReply) GetValue() *GameDetail {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteGameRequest) Reset() {
	*x = DeleteGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameRequest) ProtoMessage() {}

func (x *DeleteGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameRequest) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteGameRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteGameReply) Reset() {
	*x = DeleteGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameReply) ProtoMessage() {}

func (x *DeleteGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_tmdatabase_tmdatabase_rr_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameReply.ProtoReflect.Descriptor instead.
func (*DeleteGameReply) Descriptor() ([]byte, []int) {
	return file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteGameReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_tmdatabase_tmdatabase_rr_proto protoreflect.FileDescriptor

var file_tmdatabase_tmdatabase_rr_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x74, 0x6d, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x22, 0x74, 0x6d,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x56, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x6d,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x2d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x66, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x33, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x73, 0x0a, 0x17, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x5c, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x6d, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5d,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x9e, 0x01,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x41,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x55, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x40, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x9a, 0x01, 0x0a, 0x0e, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x56, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x58, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0x9e, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x41, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x0f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x54, 0x4d, 0x47, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x68, 0x6b, 0x2f, 0x74, 0x6d, 0x32, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x2d, 0x67, 0x6f, 0x3b, 0x74, 0x6d, 0x32, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74, 0x6d,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tmdatabase_tmdatabase_rr_proto_rawDescOnce sync.Once
	file_tmdatabase_tmdatabase_rr_proto_rawDescData = file_tmdatabase_tmdatabase_rr_proto_rawDesc
)

func file_tmdatabase_tmdatabase_rr_proto_rawDescGZIP() []byte {
	file_tmdatabase_tmdatabase_rr_proto_rawDescOnce.Do(func() {
		file_tmdatabase_tmdatabase_rr_proto_rawDescData = protoimpl.X.CompressGZIP(file_tmdatabase_tmdatabase_rr_proto_rawDescData)
	})
	return file_tmdatabase_tmdatabase_rr_proto_rawDescData
}

var file_tmdatabase_tmdatabase_rr_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_tmdatabase_tmdatabase_rr_proto_goTypes = []interface{}{
	(*GetUserBasicRequest)(nil),         // 0: tmdatabase.GetUserBasicRequest
	(*GetUserBasicReply)(nil),           // 1: tmdatabase.GetUserBasicReply
	(*GetUserBalanceRequest)(nil),       // 2: tmdatabase.GetUserBalanceRequest
	(*GetUserBalanceReply)(nil),         // 3: tmdatabase.GetUserBalanceReply
	(*GetUserStartGameInfoRequest)(nil), // 4: tmdatabase.GetUserStartGameInfoRequest
	(*GetUserStartGameInfoReply)(nil),   // 5: tmdatabase.GetUserStartGameInfoReply
	(*CreateBotPlayersRequest)(nil),     // 6: tmdatabase.CreateBotPlayersRequest
	(*CreateBotPlayersReply)(nil),       // 7: tmdatabase.CreateBotPlayersReply
	(*ListBotPlayersRequest)(nil),       // 8: tmdatabase.ListBotPlayersRequest
	(*ListBotPlayersReply)(nil),         // 9: tmdatabase.ListBotPlayersReply
	(*CreateGameRequest)(nil),           // 10: tmdatabase.CreateGameRequest
	(*CreateGameReply)(nil),             // 11: tmdatabase.CreateGameReply
	(*ListGamesRequest)(nil),            // 12: tmdatabase.ListGamesRequest
	(*ListGamesReply)(nil),              // 13: tmdatabase.ListGamesReply
	(*GetGameByIDRequest)(nil),          // 14: tmdatabase.GetGameByIDRequest
	(*GetGameByIDReply)(nil),            // 15: tmdatabase.GetGameByIDReply
	(*GetGameByNameRequest)(nil),        // 16: tmdatabase.GetGameByNameRequest
	(*GetGameByNameReply)(nil),          // 17: tmdatabase.GetGameByNameReply
	(*UpdateGameRequest)(nil),           // 18: tmdatabase.UpdateGameRequest
	(*UpdateGameReply)(nil),             // 19: tmdatabase.UpdateGameReply
	(*DeleteGameRequest)(nil),           // 20: tmdatabase.DeleteGameRequest
	(*DeleteGameReply)(nil),             // 21: tmdatabase.DeleteGameReply
	(*UserBasic)(nil),                   // 22: tmdatabase.UserBasic
	(*UserBalance)(nil),                 // 23: tmdatabase.UserBalance
	(*UserStartGameInfo)(nil),           // 24: tmdatabase.UserStartGameInfo
	(*GameDetail)(nil),                  // 25: tmdatabase.GameDetail
}
var file_tmdatabase_tmdatabase_rr_proto_depIdxs = []int32{
	22, // 0: tmdatabase.GetUserBasicReply.value:type_name -> tmdatabase.UserBasic
	23, // 1: tmdatabase.GetUserBalanceReply.value:type_name -> tmdatabase.UserBalance
	24, // 2: tmdatabase.GetUserStartGameInfoReply.value:type_name -> tmdatabase.UserStartGameInfo
	22, // 3: tmdatabase.CreateBotPlayersReply.values:type_name -> tmdatabase.UserBasic
	22, // 4: tmdatabase.ListBotPlayersReply.values:type_name -> tmdatabase.UserBasic
	25, // 5: tmdatabase.CreateGameRequest.value:type_name -> tmdatabase.GameDetail
	25, // 6: tmdatabase.CreateGameReply.value:type_name -> tmdatabase.GameDetail
	25, // 7: tmdatabase.ListGamesReply.values:type_name -> tmdatabase.GameDetail
	25, // 8: tmdatabase.GetGameByIDReply.value:type_name -> tmdatabase.GameDetail
	25, // 9: tmdatabase.GetGameByNameReply.values:type_name -> tmdatabase.GameDetail
	25, // 10: tmdatabase.UpdateGameRequest.value:type_name -> tmdatabase.GameDetail
	25, // 11: tmdatabase.UpdateGameReply.value:type_name -> tmdatabase.GameDetail
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_tmdatabase_tmdatabase_rr_proto_init() }
func file_tmdatabase_tmdatabase_rr_proto_init() {
	if File_tmdatabase_tmdatabase_rr_proto != nil {
		return
	}
	file_tmdatabase_tmdatabase_struct_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBalanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserStartGameInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserStartGameInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBotPlayersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBotPlayersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBotPlayersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBotPlayersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGamesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameByIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameByNameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmdatabase_tmdatabase_rr_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tmdatabase_tmdatabase_rr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tmdatabase_tmdatabase_rr_proto_goTypes,
		DependencyIndexes: file_tmdatabase_tmdatabase_rr_proto_depIdxs,
		MessageInfos:      file_tmdatabase_tmdatabase_rr_proto_msgTypes,
	}.Build()
	File_tmdatabase_tmdatabase_rr_proto = out.File
	file_tmdatabase_tmdatabase_rr_proto_rawDesc = nil
	file_tmdatabase_tmdatabase_rr_proto_goTypes = nil
	file_tmdatabase_tmdatabase_rr_proto_depIdxs = nil
}
