// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.3
// source: gateway/gateway_rr.proto

package tm2_proto_gateway

import (
	tm2_proto_tmdatabase_go "github.com/TMGaminghk/tm2-proto-tmdatabase-go"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserBasicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserBasicRequest) Reset() {
	*x = GetUserBasicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gateway_rr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicRequest) ProtoMessage() {}

func (x *GetUserBasicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_rr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicRequest.ProtoReflect.Descriptor instead.
func (*GetUserBasicRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_rr_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserBasicRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserBasicReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *tm2_proto_tmdatabase_go.UserBasic `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error string                             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetUserBasicReply) Reset() {
	*x = GetUserBasicReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gateway_rr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBasicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicReply) ProtoMessage() {}

func (x *GetUserBasicReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_rr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicReply.ProtoReflect.Descriptor instead.
func (*GetUserBasicReply) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_rr_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserBasicReply) GetValue() *tm2_proto_tmdatabase_go.UserBasic {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetUserBasicReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUserBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserBalanceRequest) Reset() {
	*x = GetUserBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gateway_rr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceRequest) ProtoMessage() {}

func (x *GetUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_rr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_rr_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBalanceRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserBalanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *tm2_proto_tmdatabase_go.UserBalance `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error string                               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetUserBalanceReply) Reset() {
	*x = GetUserBalanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gateway_rr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceReply) ProtoMessage() {}

func (x *GetUserBalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_rr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceReply.ProtoReflect.Descriptor instead.
func (*GetUserBalanceReply) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_rr_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserBalanceReply) GetValue() *tm2_proto_tmdatabase_go.UserBalance {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetUserBalanceReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_gateway_gateway_rr_proto protoreflect.FileDescriptor

var file_gateway_gateway_rr_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x5f, 0x72, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x1a, 0x22, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f,
	0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x56,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x5a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x6d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x3e, 0x5a, 0x3c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x4d, 0x47, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x68, 0x6b, 0x2f, 0x74, 0x6d, 0x32, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x67, 0x6f, 0x3b, 0x74, 0x6d, 0x32, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_gateway_gateway_rr_proto_rawDescOnce sync.Once
	file_gateway_gateway_rr_proto_rawDescData = file_gateway_gateway_rr_proto_rawDesc
)

func file_gateway_gateway_rr_proto_rawDescGZIP() []byte {
	file_gateway_gateway_rr_proto_rawDescOnce.Do(func() {
		file_gateway_gateway_rr_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_gateway_rr_proto_rawDescData)
	})
	return file_gateway_gateway_rr_proto_rawDescData
}

var file_gateway_gateway_rr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gateway_gateway_rr_proto_goTypes = []interface{}{
	(*GetUserBasicRequest)(nil),                 // 0: gateway.GetUserBasicRequest
	(*GetUserBasicReply)(nil),                   // 1: gateway.GetUserBasicReply
	(*GetUserBalanceRequest)(nil),               // 2: gateway.GetUserBalanceRequest
	(*GetUserBalanceReply)(nil),                 // 3: gateway.GetUserBalanceReply
	(*tm2_proto_tmdatabase_go.UserBasic)(nil),   // 4: tmdatabase.UserBasic
	(*tm2_proto_tmdatabase_go.UserBalance)(nil), // 5: tmdatabase.UserBalance
}
var file_gateway_gateway_rr_proto_depIdxs = []int32{
	4, // 0: gateway.GetUserBasicReply.value:type_name -> tmdatabase.UserBasic
	5, // 1: gateway.GetUserBalanceReply.value:type_name -> tmdatabase.UserBalance
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gateway_gateway_rr_proto_init() }
func file_gateway_gateway_rr_proto_init() {
	if File_gateway_gateway_rr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_gateway_rr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_gateway_rr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBasicReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_gateway_rr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_gateway_rr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBalanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_gateway_rr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_gateway_rr_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_rr_proto_depIdxs,
		MessageInfos:      file_gateway_gateway_rr_proto_msgTypes,
	}.Build()
	File_gateway_gateway_rr_proto = out.File
	file_gateway_gateway_rr_proto_rawDesc = nil
	file_gateway_gateway_rr_proto_goTypes = nil
	file_gateway_gateway_rr_proto_depIdxs = nil
}
